name: mykantin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  firebase_auth_web: ^5.13.5
  firebase_database: ^11.2.0
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.6.0
  cloud_firestore_web: ^4.4.0
  firebase_storage_web: ^3.10.6
  image_picker: ^0.8.7+3
  http: ^1.2.2
  intl: ^0.18.0
  url_launcher: ^6.1.14
  midtrans_sdk: ^0.4.0
  webview_flutter: ^4.4.2  # hanya menggunakan satu package webview_flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
